language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

before_install: phpenv config-rm xdebug.ini || true
install: composer install --no-progress --no-interaction
script: scripts/travis
after_script: scripts/travis-after
deploy:
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.3'
          branch: master
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.3'
          tags: true

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.3

cache:
    directories:
        - $HOME/.composer

sudo: false
